version: "3.9"

services:
  backend:
    build:
      context: ./Backend
    container_name: text_to_sql_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
    container_name: text_to_sql_frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend
